### ISSUE TITLE
about event_type

### ISSUE THREAD

**Issue by hyqer** [BGasperov/drlformm#1]
hi, Gasperov,
It seems that there is a issue when you want to discard a event  in some cases:
```
               if random.random() >= sum(self.intensities)/sum(oldintensities): # discard the event in this case
                    event_type == 0
```
when i change the code to   event_type = 0, the rewords of training become much more stable. I am not sure if it will change any conclusions in your paper. 
thanks.

**Comment by BGasperov** [comment]
Just to reply - it's been fixed, shouldn't affect the results as I did some debugging before running it. Thanks a lot.
