### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by sergiogcharles** [BGasperov/drlformm#2]
Hi there, 

We are trying to run the Jupyter notebook; however, we are running into a lot of issues with stable-baselines, which seems to be deprecated/discontinued. Namely, we are getting a lot of errors like 'No module named 'tensorflow.contrib'. Would you be able to include your requirements in a requirements.txt?

Thanks!

**Comment by sergiogcharles** [comment]
Resolved, we used 'stable-baslines3'

**Comment by huypham1103** [comment]
> Resolved, we used 'stable-baslines3'

Hi, Can you run these codes entirely?
